### ISSUE TITLE
Promoter or Re-Distributor

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-software-use-cases#1]
Section [3.4. ](https://ietf-wg-scitt.github.io/draft-ietf-scitt-software-use-cases/draft-ietf-scitt-software-use-cases.html#section-3.4)[Promotion of a Software Component by multiple entities](https://ietf-wg-scitt.github.io/draft-ietf-scitt-software-use-cases/draft-ietf-scitt-software-use-cases.html#name-promotion-of-a-software-com) refers to a **Promoter** as an entity. 

Is this the best way to reference an entity that consumes and re-distributes a package? Are they "promoting" it, which could suggest advertising or some other means to attract users to consume the specific package? Or, are they "re-distributing" a component, and various versions of the component?

**Comment by OR13** [comment]
Seems like distributor would be a better term

**Comment by SteveLasker** [comment]
@OR13 to confirm, you're suggesting distributor, as opposed to re-distributor?

**Comment by aj-stein-nist** [comment]
Reviewing old issues, should we not reintroduce obsolete terms for roles and functions not in the arch, so close this?
